# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomi < Formula
  desc "Branch delete tool made by Golang"
  homepage "https://jiko21.me/Gomi"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jiko21/Gomi/releases/download/v0.3.3/Gomi_darwin_arm64.tar.gz"
      sha256 "79da16b0dcd6eb62e24e0dee20e6bb10b669e1e68387e4116ce62cfd9e0e169d"

      def install
        bin.install "gomi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jiko21/Gomi/releases/download/v0.3.3/Gomi_darwin_x86_64.tar.gz"
      sha256 "ed62b8d45f3b98e941748cf9b063b066dbb976dbffcda2ba042b09d45ad3cf80"

      def install
        bin.install "gomi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jiko21/Gomi/releases/download/v0.3.3/Gomi_linux_x86_64.tar.gz"
      sha256 "2ed95a66c9b87ec521a7160c928d6e877762f5ae94b145343ff08279357d490c"

      def install
        bin.install "gomi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jiko21/Gomi/releases/download/v0.3.3/Gomi_linux_arm64.tar.gz"
      sha256 "2e89f07bfebb5cd01a9d89e50bbabdd97aab275a935b3bb76e11277b006506c2"

      def install
        bin.install "gomi"
      end
    end
  end
end
