# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomi < Formula
  desc "Branch delete tool made by Golang"
  homepage "https://jiko21.me/Gomi"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jiko21/Gomi/releases/download/v1.0.0/Gomi_1.0.0_macOS_x86_64.tar.gz"
      sha256 "38782698b1e4fa52f5f2e472de11a4e1fe0e5b0f170b47379457efafa909229e"

      def install
        bin.install "gomi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jiko21/Gomi/releases/download/v1.0.0/Gomi_1.0.0_macOS_arm64.tar.gz"
      sha256 "fdeeed220e0ad2b818ea5d18522e4888427aa689b310000d9ebb3aa20f0cd60e"

      def install
        bin.install "gomi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jiko21/Gomi/releases/download/v1.0.0/Gomi_1.0.0_Linux_arm64.tar.gz"
      sha256 "a70cdc8f3b426ca7bd472054fdbd842106121d9dc2dfb37ac9efef587c6cdc87"

      def install
        bin.install "gomi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jiko21/Gomi/releases/download/v1.0.0/Gomi_1.0.0_Linux_x86_64.tar.gz"
      sha256 "6e67a9708923a3d464ea8e16fa9f7740fc9fcacf19356ae0dc5e5aa9b6e0ce62"

      def install
        bin.install "gomi"
      end
    end
  end
end
